tap "dart-lang/dart"
tap "getsentry/tools"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ngrok/ngrok"
# Generic-purpose lossless compression algorithm by Google
brew "brotli"
# Asynchronous DNS library
brew "c-ares"
# Mozilla CA certificate store
brew "ca-certificates"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Core application library for C
brew "glib"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Tool to obtain certs from Let's Encrypt and autoenable HTTPS
brew "certbot"
# Statistics utility to count lines of code
brew "cloc"
# Library for USB device access
brew "libusb"
# USB programmer
brew "dfu-util"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Programming language for highly scalable real-time systems
brew "erlang"
# Open-source formatting library for C++
brew "fmt"
# Collection of reusable C++ library artifacts developed at Facebook
brew "folly"
# C++14 implementation of the TLS-1.3 standard
brew "fizz"
# Modular, composable client/server abstractions framework
brew "wangle"
# Facebook's branch of Apache Thrift, including a new C++ server
brew "fbthrift"
# Thrift functions for querying information from a service
brew "fb303"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl2"
# H.264/AVC encoder
brew "x264"
# High-performance, asynchronous messaging library
brew "zeromq"
# Scaling, colorspace conversion, and dithering library
brew "zimg"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git-powered FTP client
brew "git-ftp"
# Git extension for versioning large files
brew "git-lfs"
# Alternative to top/htop
brew "glances"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Library for manipulating JPEG-2000 images
brew "jasper"
# Image manipulation
brew "netpbm"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Kubernetes package manager
brew "helm"
# Platform built on V8 to build network applications
brew "node"
# Simple zero-configuration command-line HTTP server
brew "http-server"
# Add GitHub support to git on the command-line
brew "hub"
# Migrate or backup IMAP mail accounts
brew "imapsync"
# Image loading and rendering library
brew "imlib2"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Tool to move from `docker-compose` to Kubernetes
brew "kompose"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Sophisticated file transfer program
brew "lftp"
# Run a Kubernetes cluster locally
brew "minikube"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# MongoDB Shell to connect, configure, query, and work with your MongoDB database
brew "mongosh"
# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"
# HTTP/2 C Library
brew "nghttp2"
# Port scanning utility for large networks
brew "nmap"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# H.264 codec from Cisco
brew "openh264"
# Development kit for the Java programming language
brew "openjdk"
# Object-relational database system
brew "postgresql"
# Pretty, minimal and fast ZSH prompt
brew "pure"
# Python version management
brew "pyenv"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Sentry command-line client for some generic tasks
brew "getsentry/tools/sentry-cli"
# Terraform
brew "hashicorp/tap/terraform"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# 3D creation suite
cask "blender"
# API documentation browser and code snippet manager
cask "dash"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# VPN client for secure internet access and private browsing
cask "expressvpn"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Client for the Google Drive storage service
cask "google-drive"
# Open-source video transcoder
cask "handbrake"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Wallet desktop application to maintain multiple cryptocurrencies
cask "ledger-live"
# Support for Logitech G gear
cask "logitech-g-hub"
# Software for Logitech devices
cask "logitech-options"
# Open-source music notation software
cask "musescore"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Collaboration platform for API development
cask "postman"
# G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.)
cask "prusaslicer"
# File transfer application
cask "transmit"
# Open-source code editor
cask "visual-studio-code"
