tap "getsentry/tools"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ngrok/ngrok"
brew "brotli"
brew "c-ares"
brew "ca-certificates"
brew "python@3.10"
brew "certbot"
brew "cloc"
brew "libusb"
brew "dfu-util"
brew "docker", link: false
brew "erlang"
brew "gh"
brew "git-ftp"
brew "git-lfs"
brew "glances"
brew "go"
brew "helm"
brew "node"
brew "http-server"
brew "imapsync"
brew "oniguruma"
brew "jq"
brew "kompose"
brew "kubernetes-cli"
brew "lftp"
brew "mas"
brew "minikube"
brew "mkcert"
brew "mongosh"
brew "nmap"
brew "nvm"
brew "openjdk"
brew "postgresql"
brew "pure"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "tree"
brew "wget"
brew "getsentry/tools/sentry-cli"
brew "hashicorp/tap/terraform"
brew "heroku/brew/heroku"
cask "blender"
cask "dash"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "google-cloud-sdk"
cask "google-drive"
cask "handbrake"
cask "iterm2"
cask "ngrok"
cask "postman"
cask "prusaslicer"
cask "rectangle-pro"
cask "transmit"
cask "visual-studio-code"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Affinity Publisher", id: 881418622
mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Kaleidoscope", id: 1575557335
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
